# Generated by Django 3.2.5 on 2021-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='phil placeholder.jpg', null=True, upload_to='images/'),
        ),
    ]
