# Generated by Django 3.2.5 on 2021-07-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
